// src/product/seed.ts
// 100 products – images served from CDN (picsum.photos), data served from backend API

import { ProductDTO } from './product';

const CDN_IMAGE = (id: number) => `https://picsum.photos/seed/product-${id}/400/400`;

function categoryForId(id: number): string {
  if (id <= 18) return 'Electronics';
  if (id <= 36) return 'Home & Kitchen';
  if (id <= 54) return 'Health & Beauty';
  if (id <= 72) return 'Grocery';
  if (id <= 82) return 'Furniture';
  if (id <= 92) return 'TVs & Accessories';
  return 'Pet Supplies';
}

export const products: ProductDTO[] = [
  { id: 1, productName: 'Wireless Headphones', productCode: 'WH-001', description: 'Premium over-ear wireless headphones with noise cancellation', price: 99.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(1), category: categoryForId(1) },
  { id: 2, productName: 'Smart Watch', productCode: 'SW-002', description: 'Fitness and health tracking smartwatch with GPS', price: 149.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(2), category: categoryForId(2) },
  { id: 3, productName: 'Bluetooth Speaker', productCode: 'BS-003', description: 'Portable waterproof Bluetooth speaker', price: 79.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(3), category: categoryForId(3) },
  { id: 4, productName: 'Gaming Mouse', productCode: 'GM-004', description: 'RGB gaming mouse with 16000 DPI', price: 49.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(4) },
  { id: 5, productName: 'Mechanical Keyboard', productCode: 'MK-005', description: 'Cherry MX mechanical gaming keyboard', price: 129.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(5), category: categoryForId(5) },
  { id: 6, productName: 'HD Webcam', productCode: 'WC-006', description: '1080p streaming webcam with built-in mic', price: 59.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(6), category: categoryForId(6) },
  { id: 7, productName: 'Portable Charger', productCode: 'PC-007', description: '20000mAh fast-charge power bank', price: 39.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(7), category: categoryForId(7) },
  { id: 8, productName: 'VR Headset', productCode: 'VR-008', description: 'Immersive VR headset for gaming', price: 299.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(8), category: categoryForId(8) },
  { id: 9, productName: 'Smartphone Gimbal', productCode: 'SG-009', description: '3-axis smartphone stabilizer', price: 89.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(9), category: categoryForId(9) },
  { id: 10, productName: 'Action Camera', productCode: 'AC-010', description: '4K waterproof action camera', price: 199.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(10), category: categoryForId(10) },
  { id: 11, productName: 'Noise Cancelling Earbuds', productCode: 'EB-011', description: 'True wireless earbuds with ANC', price: 119.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(11), category: categoryForId(11) },
  { id: 12, productName: 'Laptop Stand', productCode: 'LS-012', description: 'Adjustable aluminum laptop stand', price: 49.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(12), category: categoryForId(12) },
  { id: 13, productName: 'External Hard Drive', productCode: 'HD-013', description: '2TB portable SSD USB 3.2', price: 89.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(13) },
  { id: 14, productName: 'Smart Light Bulb', productCode: 'LB-014', description: 'Wi-Fi color smart bulb pack of 4', price: 29.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(14), category: categoryForId(14) },
  { id: 15, productName: 'Fitness Tracker', productCode: 'FT-015', description: 'Water-resistant fitness band', price: 59.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(15) },
  { id: 16, productName: 'Wireless Charger', productCode: 'WC-016', description: '15W Qi wireless charging pad', price: 39.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(16), category: categoryForId(16) },
  { id: 17, productName: 'Digital Photo Frame', productCode: 'PF-017', description: '10-inch cloud-connected digital frame', price: 79.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(17), category: categoryForId(17) },
  { id: 18, productName: 'Portable Projector', productCode: 'PJ-018', description: 'Mini LED portable projector 1080p', price: 249.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(18), category: categoryForId(18) },
  { id: 19, productName: 'Smart Thermostat', productCode: 'ST-019', description: 'Learning Wi-Fi thermostat', price: 199.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(19) },
  { id: 20, productName: 'Tablet Stand', productCode: 'TS-020', description: 'Adjustable tablet holder for desk', price: 34.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(20), category: categoryForId(20) },
  { id: 21, productName: 'USB-C Hub', productCode: 'UH-021', description: '7-in-1 USB-C hub with HDMI', price: 54.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(21), category: categoryForId(21) },
  { id: 22, productName: 'Ring Light', productCode: 'RL-022', description: '10-inch LED ring light with stand', price: 44.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(22), category: categoryForId(22) },
  { id: 23, productName: 'Desk Organizer', productCode: 'DO-023', description: 'Bamboo desk organizer with wireless charger', price: 35.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(23) },
  { id: 24, productName: 'Monitor Arm', productCode: 'MA-024', description: 'Dual monitor gas spring arm', price: 89.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(24), category: categoryForId(24) },
  { id: 25, productName: 'Ergonomic Mouse', productCode: 'EM-025', description: 'Vertical ergonomic wireless mouse', price: 45.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(25), category: categoryForId(25) },
  { id: 26, productName: 'Desk Mat', productCode: 'DM-026', description: 'Large leather desk mat with stitched edges', price: 32.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(26) },
  { id: 27, productName: 'Screen Cleaner Kit', productCode: 'SC-027', description: 'Microfiber and spray screen cleaning kit', price: 14.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(27), category: categoryForId(27) },
  { id: 28, productName: 'Cable Management', productCode: 'CM-028', description: 'Cable clips and sleeve kit', price: 19.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(28), category: categoryForId(28) },
  { id: 29, productName: 'Blue Light Glasses', productCode: 'BL-029', description: 'Anti-blue light computer glasses', price: 24.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(29) },
  { id: 30, productName: 'Laptop Sleeve', productCode: 'LPS-030', description: 'Neoprene laptop sleeve 13–15 inch', price: 28.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(30), category: categoryForId(30) },
  { id: 31, productName: 'Phone Holder', productCode: 'PH-031', description: 'Adjustable phone stand for desk', price: 16.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(31), category: categoryForId(31) },
  { id: 32, productName: 'Headphone Stand', productCode: 'HS-032', description: 'Aluminum headphone stand with base', price: 29.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(32) },
  { id: 33, productName: 'Webcam Cover', productCode: 'WCO-033', description: 'Sliding webcam privacy cover', price: 9.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(33), category: categoryForId(33) },
  { id: 34, productName: 'USB Desk Fan', productCode: 'UF-034', description: 'Quiet USB desk fan with 3 speeds', price: 22.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(34), category: categoryForId(34) },
  { id: 35, productName: 'Desk Lamp', productCode: 'DL-035', description: 'LED desk lamp with USB port', price: 38.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(35) },
  { id: 36, productName: 'Wrist Rest', productCode: 'WR-036', description: 'Ergonomic memory foam wrist rest', price: 18.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(36), category: categoryForId(36) },
  { id: 37, productName: 'Foot Rest', productCode: 'FR-037', description: 'Adjustable under-desk foot rest', price: 34.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(37) },
  { id: 38, productName: 'Document Holder', productCode: 'DH-038', description: 'Copy holder for desk', price: 26.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(38), category: categoryForId(38) },
  { id: 39, productName: 'Whiteboard', productCode: 'WB-039', description: 'Small desktop whiteboard with markers', price: 21.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(39), category: categoryForId(39) },
  { id: 40, productName: 'Sticky Notes Set', productCode: 'SN-040', description: 'Assorted sticky notes and flags', price: 11.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(40), category: categoryForId(40) },
  { id: 41, productName: 'Pen Holder', productCode: 'PEH-041', description: 'Minimalist pen and pencil holder', price: 15.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(41), category: categoryForId(41) },
  { id: 42, productName: 'Notebook Set', productCode: 'NB-042', description: 'Pack of 3 ruled A5 notebooks', price: 12.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(42), category: categoryForId(42) },
  { id: 43, productName: 'Laptop Cooling Pad', productCode: 'LCP-043', description: '5-fan USB laptop cooling pad', price: 36.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(43), category: categoryForId(43) },
  { id: 44, productName: 'HDMI Cable', productCode: 'HC-044', description: 'HDMI 2.0 cable 6ft', price: 12.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(44), category: categoryForId(44) },
  { id: 45, productName: 'Ethernet Cable', productCode: 'EC-045', description: 'Cat 6 Ethernet cable 10ft', price: 9.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(45) },
  { id: 46, productName: 'Adapter Set', productCode: 'AS-046', description: 'USB-C to USB-A and HDMI adapter', price: 24.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(46), category: categoryForId(46) },
  { id: 47, productName: 'SD Card Reader', productCode: 'SD-047', description: 'USB 3.0 multi-card reader', price: 17.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(47), category: categoryForId(47) },
  { id: 48, productName: 'Docking Station', productCode: 'DS-048', description: 'USB-C docking station dual 4K', price: 159.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(48) },
  { id: 49, productName: 'Microphone', productCode: 'MIC-049', description: 'USB condenser microphone for streaming', price: 69.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(49), category: categoryForId(49) },
  { id: 50, productName: 'Pop Filter', productCode: 'PF-050', description: 'Microphone pop filter with clamp', price: 14.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(50), category: categoryForId(50) },
  { id: 51, productName: 'Streaming Light', productCode: 'SL-051', description: 'LED panel light for streaming', price: 54.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(51), category: categoryForId(51) },
  { id: 52, productName: 'Green Screen', productCode: 'GS-052', description: 'Collapsible green screen backdrop', price: 42.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(52) },
  { id: 53, productName: 'Controller', productCode: 'CT-053', description: 'Wireless game controller', price: 44.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(53), category: categoryForId(53) },
  { id: 54, productName: 'Controller Charger', productCode: 'CC-054', description: 'Dual controller charging dock', price: 29.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(54) },
  { id: 55, productName: 'Gaming Headset', productCode: 'GH-055', description: '7.1 surround gaming headset', price: 79.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(55), category: categoryForId(55) },
  { id: 56, productName: 'Mouse Pad', productCode: 'MP-056', description: 'Extended RGB mouse pad', price: 26.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(56), category: categoryForId(56) },
  { id: 57, productName: 'Keycap Set', productCode: 'KS-057', description: 'PBT keycap set for mechanical keyboards', price: 49.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(57) },
  { id: 58, productName: 'Laptop Bag', productCode: 'LB-058', description: 'Water-resistant laptop messenger bag', price: 59.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(58), category: categoryForId(58) },
  { id: 59, productName: 'Backpack', productCode: 'BP-059', description: 'Laptop backpack with USB charging', price: 64.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(59) },
  { id: 60, productName: 'Card Reader', productCode: 'CR-060', description: 'Compact USB-C card reader', price: 19.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(60), category: categoryForId(60) },
  { id: 61, productName: 'Smart Plug', productCode: 'SP-061', description: 'Wi-Fi smart plug 2-pack', price: 24.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(61), category: categoryForId(61) },
  { id: 62, productName: 'Doorbell Camera', productCode: 'DC-062', description: 'Wireless video doorbell', price: 129.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(62) },
  { id: 63, productName: 'Security Camera', productCode: 'SEC-063', description: 'Indoor 1080p security camera', price: 39.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(63), category: categoryForId(63) },
  { id: 64, productName: 'Smart Lock', productCode: 'SML-064', description: 'Keypad smart door lock', price: 149.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(64), category: categoryForId(64) },
  { id: 65, productName: 'Robot Vacuum', productCode: 'RV-065', description: 'Wi-Fi robot vacuum cleaner', price: 249.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(65), category: categoryForId(65) },
  { id: 66, productName: 'Air Purifier', productCode: 'AP-066', description: 'HEPA air purifier for rooms', price: 89.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(66), category: categoryForId(66) },
  { id: 67, productName: 'Humidifier', productCode: 'HM-067', description: 'Ultrasonic cool mist humidifier', price: 44.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(67) },
  { id: 68, productName: 'Smart Scale', productCode: 'SS-068', description: 'Bluetooth body composition scale', price: 34.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(68), category: categoryForId(68) },
  { id: 69, productName: 'Electric Kettle', productCode: 'EK-069', description: 'Temperature control electric kettle', price: 49.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(69), category: categoryForId(69) },
  { id: 70, productName: 'Coffee Maker', productCode: 'CF-070', description: 'Single-serve coffee maker', price: 79.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(70), category: categoryForId(70) },
  { id: 71, productName: 'Blender', productCode: 'BL-071', description: 'Personal size blender', price: 39.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(71), category: categoryForId(71) },
  { id: 72, productName: 'Desk Treadmill', productCode: 'DT-072', description: 'Under-desk walking treadmill', price: 349.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(72) },
  { id: 73, productName: 'Resistance Bands', productCode: 'RB-073', description: 'Set of 5 resistance bands', price: 24.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(73), category: categoryForId(73) },
  { id: 74, productName: 'Yoga Mat', productCode: 'YM-074', description: 'Non-slip exercise yoga mat', price: 29.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(74) },
  { id: 75, productName: 'Water Bottle', productCode: 'WBT-075', description: 'Insulated stainless steel bottle', price: 34.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(75), category: categoryForId(75) },
  { id: 76, productName: 'Lunch Box', productCode: 'LX-076', description: 'Insulated bento lunch box', price: 28.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(76) },
  { id: 77, productName: 'Desk Plant', productCode: 'DP-077', description: 'Low-light desk plant in pot', price: 22.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(77), category: categoryForId(77) },
  { id: 78, productName: 'Desk Vacuum', productCode: 'DV-078', description: 'Mini USB desk vacuum', price: 26.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(78), category: categoryForId(78) },
  { id: 79, productName: 'Hand Sanitizer Stand', productCode: 'HSS-079', description: 'Automatic touchless sanitizer dispenser', price: 32.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(79) },
  { id: 80, productName: 'Desk Clock', productCode: 'DCL-080', description: 'LED digital desk clock', price: 18.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(80), category: categoryForId(80) },
  { id: 81, productName: 'Calendar Board', productCode: 'CB-081', description: 'Dry-erase wall calendar', price: 27.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(81), category: categoryForId(81) },
  { id: 82, productName: 'Book Stand', productCode: 'BKS-082', description: 'Adjustable book and tablet stand', price: 23.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(82), category: categoryForId(82) },
  { id: 83, productName: 'Letter Tray', productCode: 'LT-083', description: 'Stacking file letter tray', price: 19.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(83), category: categoryForId(83) },
  { id: 84, productName: 'Shredder', productCode: 'SHR-084', description: 'Cross-cut paper shredder', price: 54.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(84), category: categoryForId(84) },
  { id: 85, productName: 'Label Maker', productCode: 'LM-085', description: 'Portable label maker', price: 34.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(85), category: categoryForId(85) },
  { id: 86, productName: 'Stapler', productCode: 'STP-086', description: 'Heavy-duty metal stapler', price: 24.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(86), category: categoryForId(86) },
  { id: 87, productName: 'Scanner', productCode: 'SCN-087', description: 'Portable document scanner', price: 99.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(87), category: categoryForId(87) },
  { id: 88, productName: 'Printer', productCode: 'PR-088', description: 'All-in-one wireless printer', price: 129.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(88), category: categoryForId(88) },
  { id: 89, productName: 'Ink Cartridges', productCode: 'IC-089', description: 'Printer ink cartridge 2-pack', price: 44.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(89), category: categoryForId(89) },
  { id: 90, productName: 'Paper Ream', productCode: 'PR-090', description: 'Letter size copy paper 500 sheets', price: 8.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(90), category: categoryForId(90) },
  { id: 91, productName: 'Sticky Notes Dispenser', productCode: 'SND-091', description: 'Desktop sticky notes dispenser', price: 13.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(91), category: categoryForId(91) },
  { id: 92, productName: 'Highlighters Set', productCode: 'HL-092', description: 'Assorted highlighters 6-pack', price: 9.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(92), category: categoryForId(92) },
  { id: 93, productName: 'Ballpoint Pens', productCode: 'BPP-093', description: 'Smooth ballpoint pens 12-pack', price: 11.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(93) },
  { id: 94, productName: 'Sticky Tabs', productCode: 'ST-094', description: 'Color-coded index tabs', price: 7.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(94), category: categoryForId(94) },
  { id: 95, productName: 'Folder Set', productCode: 'FS-095', description: 'Manila file folders 25-pack', price: 14.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(95), category: categoryForId(95) },
  { id: 96, productName: 'Clipboard', productCode: 'CL-096', description: 'Plastic clipboard with clip', price: 6.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(96) },
  { id: 97, productName: 'Calculator', productCode: 'CAL-097', description: 'Desktop calculator with large display', price: 19.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(97), category: categoryForId(97) },
  { id: 98, productName: 'Paper Clips', productCode: 'PC-098', description: 'Jumbo box of paper clips', price: 5.99, quantityInStock: 50, hasReviews: false, image: CDN_IMAGE(98), category: categoryForId(98) },
  { id: 99, productName: 'Desk Caddy', productCode: 'DCA-099', description: 'Multi-compartment desk caddy', price: 21.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(99), category: categoryForId(99) },
  { id: 100, productName: 'Monitor Riser', productCode: 'MR-100', description: 'Bamboo monitor stand with storage', price: 45.99, quantityInStock: 50, hasReviews: true, image: CDN_IMAGE(100), category: categoryForId(100) },
];
