import { ReviewDTO } from './review';

const REVIEWS: ReviewDTO[] = [
  { id: 1, productId: 1, userName: 'tech_fan', title: 'Excellent sound quality', text: 'Noise cancellation is amazing. Battery lasts all day. Very comfortable for long sessions.' },
  { id: 2, productId: 1, userName: 'alice_m', title: 'Worth every penny', text: 'Best wireless headphones I have owned. Pairing is instant and the build quality is solid.' },
  { id: 3, productId: 2, userName: 'fitness_joe', title: 'Great for runs', text: 'GPS is accurate and the health metrics are really helpful. Screen is readable in sunlight.' },
  { id: 4, productId: 2, userName: 'sarah_k', title: 'Love the design', text: 'Sleek and lightweight. Notifications and calls work well. Battery lasts about 4 days.' },
  { id: 5, productId: 3, userName: 'beach_lover', title: 'Actually waterproof', text: 'Took it to the pool and it held up. Sound is loud and clear. Good bass for the size.' },
  { id: 6, productId: 4, userName: 'gamer_xyz', title: 'Precise and responsive', text: '16000 DPI is overkill but the sensor is flawless. RGB looks great. No lag.' },
  { id: 7, productId: 5, userName: 'thor364', title: 'Solid build', text: 'Cherry MX keys feel great. Sturdy frame. Good for both typing and gaming.' },
  { id: 8, productId: 5, userName: 'coder_99', title: 'Did not work as expected', text: 'Keys are good but the software was tricky to set up. Once configured it is fine.' },
  { id: 9, productId: 7, userName: 'traveler', title: 'Saves my phone daily', text: '20000mAh gets me through 3–4 full charges. Fast charge works as advertised.' },
  { id: 10, productId: 8, userName: 'vr_enthusiast', title: 'Immersive experience', text: 'Setup was easy. Picture is clear and tracking is smooth. Great for sim racing.' },
  { id: 11, productId: 9, userName: 'vlogger', title: 'Smooth footage', text: '3-axis stabilization really works. My walking shots look professional now.' },
  { id: 12, productId: 10, userName: 'jackharkness', title: 'Works great', text: "I've beat every level faster with this. 4K looks sharp and it is durable." },
  { id: 13, productId: 10, userName: 'outdoor_fan', title: 'Tough little camera', text: 'Waterproof seal is solid. Battery could be better but image quality is top.' },
  { id: 14, productId: 11, userName: 'commuter', title: 'ANC is a game changer', text: 'Train noise almost gone. Fit is secure. Case is compact.' },
  { id: 15, productId: 13, userName: 'backup_pro', title: 'Fast and reliable', text: '2TB is plenty. Transfer speeds are as stated. No issues so far.' },
  { id: 16, productId: 14, userName: 'smart_home', title: 'Easy to set up', text: 'App is simple. Colors are vibrant. Schedules and routines work well.' },
  { id: 17, productId: 15, userName: 'runner_me', title: 'Accurate heart rate', text: 'Water resistant and light. Sleep tracking is useful. Good value.' },
  { id: 18, productId: 17, userName: 'grandma_s', title: 'Great for grandkids photos', text: 'Cloud upload is easy. Display is bright. Family loves it.' },
  { id: 19, productId: 18, userName: 'presenter', title: 'Bright enough for day use', text: 'Portable and quick to set up. Good for small meetings. Sound is okay.' },
  { id: 20, productId: 19, userName: 'home_owner', title: 'Learned our schedule', text: 'Saves on heating. Installation was straightforward. App is intuitive.' },
  { id: 21, productId: 21, userName: 'laptop_user', title: 'All ports in one', text: 'HDMI 4K works. No power issues. Build is solid for the price.' },
  { id: 22, productId: 22, userName: 'streamer_new', title: 'Nice even light', text: 'Adjustable brightness and color temp. No flicker on camera. Good for Zoom.' },
  { id: 23, productId: 24, userName: 'dual_monitor', title: 'Sturdy arm', text: 'Holds two 27" monitors with no sag. Cable management included. Easy to adjust.' },
  { id: 24, productId: 25, userName: 'wrist_pain', title: 'Ergonomic relief', text: 'Vertical angle really helps. Wireless has no delay. Would buy again.' },
  { id: 25, productId: 27, userName: 'clean_freak', title: 'Streak-free screens', text: 'Microfiber is soft and the spray does not damage coatings. Good kit.' },
  { id: 26, productId: 28, userName: 'tidy_desk', title: 'Cables finally hidden', text: 'Clips and sleeve made a big difference. Desk looks clean now.' },
  { id: 27, productId: 29, userName: 'night_owl', title: 'Less eye strain', text: 'Wore them for a week and my eyes feel better at the end of the day.' },
  { id: 28, productId: 31, userName: 'desk_setup', title: 'Stable holder', text: 'Holds my large phone at a good angle. Base is heavy enough. Good value.' },
  { id: 29, productId: 32, userName: 'audiophile', title: 'Looks and works great', text: 'Sturdy aluminum. Headphones sit securely. Matches my setup.' },
  { id: 30, productId: 34, userName: 'office_worker', title: 'Quiet and effective', text: 'Three speeds are enough. Runs quiet. USB powered is convenient.' },
  { id: 31, productId: 35, userName: 'student', title: 'Good desk lamp', text: 'LED is even and bright. USB port is handy. Arm is flexible.' },
  { id: 32, productId: 36, userName: 'typer', title: 'Comfortable wrist rest', text: 'Memory foam is soft. Stays in place. Reduced wrist fatigue.' },
  { id: 33, productId: 38, userName: 'reader', title: 'Holds documents well', text: 'Copy holder is adjustable. Does not take much space. Sturdy.' },
  { id: 34, productId: 39, userName: 'planner', title: 'Handy whiteboard', text: 'Good size for desk. Markers are decent. Easy to erase.' },
  { id: 35, productId: 41, userName: 'minimalist', title: 'Simple and functional', text: 'Holds pens and pencils. Matches my desk. No complaints.' },
  { id: 36, productId: 42, userName: 'writer', title: 'Nice notebooks', text: 'Paper is smooth. Binding is solid. Good for journaling.' },
  { id: 37, productId: 43, userName: 'gamer_laptop', title: 'Cooling helps', text: 'Laptop runs a few degrees cooler. Fans are not too loud. USB powered.' },
  { id: 38, productId: 45, userName: 'network_admin', title: 'Reliable cable', text: 'Cat 6, good length. No dropouts. Good for home office.' },
  { id: 39, productId: 46, userName: 'mac_user', title: 'Adapter set works', text: 'USB-C to USB-A and HDMI both work. Compact. Good for travel.' },
  { id: 40, productId: 47, userName: 'photographer', title: 'Reads all my cards', text: 'SD and microSD work. Speeds are good. Small and portable.' },
  { id: 41, productId: 49, userName: 'podcaster', title: 'Clear microphone', text: 'USB plug and play. Sound is clear. Good for streaming and calls.' },
  { id: 42, productId: 51, userName: 'content_creator', title: 'Soft LED light', text: 'No harsh shadows. Dimmable. Good for face lighting.' },
  { id: 43, productId: 52, userName: 'streamer_pro', title: 'Easy green screen', text: 'Collapsible and portable. Wrinkles smooth out. Good for virtual backgrounds.' },
  { id: 44, productId: 53, userName: 'console_fan', title: 'Responsive controller', text: 'Wireless range is good. Battery lasts long. Comfortable grip.' },
  { id: 45, productId: 55, userName: 'gamer_audio', title: '7.1 sounds great', text: 'Surround is convincing. Mic is clear. Comfortable for long sessions.' },
  { id: 46, productId: 56, userName: 'rgb_fan', title: 'Nice extended pad', text: 'Keyboard and mouse fit. RGB is subtle. Surface is smooth.' },
  { id: 47, productId: 58, userName: 'student_bag', title: 'Fits laptop and more', text: 'Water resistant. Padded compartment. Good for daily carry.' },
  { id: 48, productId: 61, userName: 'smart_home_2', title: 'Works with Alexa', text: 'Two plugs in the pack. Scheduling and voice control work. Easy setup.' },
  { id: 49, productId: 62, userName: 'home_security', title: 'Good video doorbell', text: 'Installation was easy. Video is clear. Motion alerts are accurate.' },
  { id: 50, productId: 65, userName: 'busy_parent', title: 'Robot vacuum helps', text: 'Wi-Fi and app work well. Picks up well on hardwood. Schedules are handy.' },
];

export const reviews: ReviewDTO[] = REVIEWS;
